### ISSUE TITLE
[PW-3239] Add support for Dispute API

### ISSUE THREAD

**Issue by tddouglas** [Adyen/adyen-python-api-library#109]
Currently, Adyen Dispute API isn't supported via this library. With the recent addition of JSON support for the Dispute API, this would be a very nice add - https://docs.adyen.com/risk-management/disputes-api

**Comment by cyattilakiss** [comment]
Hi @tddouglas ,

Thank you for raising this issue, we are picking this up to our backlog.

Best,
Attila
Adyen
