### ISSUE TITLE
[PW-3240] /adjustAuthorisation is not implemented

### ISSUE THREAD

**Issue by slallema** [Adyen/adyen-python-api-library#112]
**Is your feature request related to a problem? Please describe.**
I need to modify the amount of some credit card authorisations I make 

**Describe the solution you'd like**
I would like the API call https://docs.adyen.com/api-explorer/#/Payment/v52/post/adjustAuthorisation to be supported by the python client

**Describe alternatives you've considered**
For now I create several authorisations when needed but this is suboptimal

**Comment by jillingk** [comment]
Closing the ticket as adjustAuthorisation has been implemented.
