### ISSUE TITLE
is_valid_hmac_notification incorrectly fails when there are colons in the HMAC payload components

### ISSUE THREAD

**Issue by cjtapper** [Adyen/adyen-python-api-library#117]
**Describe the bug**
HMAC validation fails when there are colons (":") in any of the components of the HMAC payload before they are seperated. Removing the `.replace(":", "\:")` here rectifies this issue:
https://github.com/Adyen/adyen-python-api-library/blob/28ab82e03c55ac2ab0e625a5e32f0a171f94804f/Adyen/util.py#L60

I'm not sure why this is the case - I can see that the Node API library does this same string replace, yet it _does_ validate a notification's HMAC signature correctly even if there are colons in the payload

**To Reproduce**
I received a notification from Adyen like: 
```json
{
    "amount": {"value": 7500, "currency": "SEK"},
    "reason": "113 No InvoiceLines provided",
    "success": "false",
    "eventCode": "AUTHORISATION",
    "eventDate": "2020-08-14T10:53:35+02:00",
    "pspReference": "853597395210930A",
    "paymentMethod": "klarna_paynow",
    "additionalData": {"hmacSignature": "FscAVupR4KdL4ecAl6VURgMUSPXJ+E1AgE3OQtukHUg="},
    "merchantReference": "14-08-2020-09:53:00",
    "merchantAccountCode": "MERCHANT_ACCOUNT_CODE",
}
```
(anonymised my merchant account code here for anonymity)

If I try to validate this using `is_valid_hmac_notification()` it fails. It succeeds if I test it with the Node JS client library. And if I remove the code mentioned above, it _does_ work in Python.

Note that I've received other notifications with no colons in the merchantReference, and those have been successfully validated.

**Comment by AlexandrosMor** [comment]
This issue is fixed and merged to the develop #118
