### ISSUE TITLE
Client uses incorrect live endpoint URLs for payments

### ISSUE THREAD

**Issue by sashakruglov** [Adyen/adyen-python-api-library#119]
**Describe the bug**
According to Adyen documentation [here](https://docs.adyen.com/development-resources/live-endpoints#standard-payments-endpoints) live endpoint URLs for payments should be of this format: 

> https://[random]-[company name]-pal-live.adyenpayments.com/pal/servlet/Payment/[version]/[method]

Checking "API URLs and Responses" configuration in Adyen live account, I see that live endpoint URLs indeed follow this pattern.

However, the Adyen client produces the following URL: 

> https://pal-live.adyen.com/pal/servlet/Payment/v49/refund

**To Reproduce**
```
from Adyen import AdyenClient
AdyenClient._determine_api_url(platform='live', service='Payment', action='refund')
u'https://pal-live.adyen.com/pal/servlet/Payment/v49/refund'
```

**Expected behavior**
Adyen library uses live_endpoint_prefix parameter to correctly format payments live endpoint URLs.

**Additional context**
LIB_VERSION = "3.0.0"
LIB_NAME = "adyen-python-api-library"

**Comment by sashakruglov** [comment]
If this is indeed a bug, I can contribute a fix for it.

**Comment by rafaelgotts** [comment]
> If this is indeed a bug, I can contribute a fix for it.

Do you still intent to fix it?

**Comment by sashakruglov** [comment]
Hi @rafaelgotts , I opened PR for this.
