### ISSUE TITLE
Idempotency support

### ISSUE THREAD

**Issue by artemijan** [Adyen/adyen-python-api-library#123]
I've noticed that this library supports Idempotency feature. But accordingly to adyen documentation it should be handled in different way, see https://docs.adyen.com/development-resources/api-idempotency.
I just need a way to pass this header (uuid) though the library, so this header can be controlled from my application.

Thank you.

**Comment by whyscream** [comment]
We're also looking for this feature.

**Comment by artemijan** [comment]
I ended up with implementing this feature on my own https://github.com/Adyen/adyen-python-api-library/commit/21f5f0b56a37835f01631ed6a294e9fff62b5539.

**Comment by whyscream** [comment]
I found this article which describes the existing implementation (in 4.0.0) as obsoleted by Adyen: https://www.adyen.help/hc/en-us/articles/360012846739

**Comment by AlexandrosMor** [comment]
Hello @artemijan,

We opened a pull request for this issue and we merged it 

regards
Alexandros

**Comment by artemijan** [comment]
Thank you a lot
