### ISSUE TITLE
PaymentCompletionDetails dict

### ISSUE THREAD

**Issue by rousseldenis** [Adyen/adyen-python-api-library#128]
**Is your feature request related to a problem? Please describe.**

Apparently, some banks 3DS services return unwanted arguments after a RedirectShopper.
This generates a 702 error when submitting that response to paymentDetails.

**Describe the solution you'd like**

As in https://github.com/Adyen/adyen-node-api-library/blob/develop/src/typings/checkout.ts#L2885, I want to 
create a dict with wanted parameters to remove unwanted ones.

This will allow to avoid bad design from third parties applications.

**Describe alternatives you've considered**

**Additional context**

**Comment by AlexandrosMor** [comment]
Hello @rousseldenis,

Thank you for raising this issue. I would like to ask to provide us with an example of this enhancement if this is still an issue for you. 

Kind regards,
Alexandros,
Adyen
