### ISSUE TITLE
[PW-4232] Support latest checkout API v67

### ISSUE THREAD

**Issue by hossam-zoover** [Adyen/adyen-python-api-library#133]
**Describe the solution you'd like**

At this moment you are supporting checkout v66 and I would like to use the latest version of the [checkout v67](https://docs.adyen.com/api-explorer/#/CheckoutService/v67)
https://github.com/Adyen/adyen-python-api-library/blob/develop/Adyen/settings.py#L10

**Comment by msilvagarcia** [comment]
Hey @hossam-zoover ! Thank you fo the suggestion. We will prioritize it internally and update this ticket when released.

Cheers!
Marcos
Adyen

**Comment by hossam-zoover** [comment]
Thanks Marcos, looking forward to it

**Comment by AlexandrosMor** [comment]
Hello @hossam-zoover, 
v67 is included in the release version 5.0.0
kind regards,
Alexandros
Adyen

**Comment by hossam-zoover** [comment]
@AlexandrosMor thanks a lot 👍🏼
