### ISSUE TITLE
[PW-5864] Support for creating Apple Pay sessions

### ISSUE THREAD

**Issue by michaszcz** [Adyen/adyen-python-api-library#143]
**Describe the solution you'd like**
I would like to use the library to create apple pay sessions, but it is not possible at the moment.

Adyen docs mention to use the following request: 

```
curl https://checkout-test.adyen.com/checkout/v64/applePay/sessions \
-H "x-API-key: YOUR_X-API-KEY" \
-H "content-type: application/json" \
-d '{
  "displayName": "YOUR_MERCHANT_NAME",
  "domainName": "window.location.hostname",
  "merchantIdentifier": "YOUR_MERCHANT_ID"
}'
```

Source:
https://docs.adyen.com/payment-methods/apple-pay/api-only#-applepay-sessions-request

**Comment by AlexandrosMor** [comment]
Hello @michaszcz,

We created an investigation ticket and we are going to pick it up as soon as possible

kind regards,
Alexandros
Adyen
