### ISSUE TITLE
[PW-5867] HMAC verification functions corrupt notification item payload

### ISSUE THREAD

**Issue by ghost** [Adyen/adyen-python-api-library#148]
**Python version**: 3.9.6
**Library version**: 5.1.0
**Description**
`Adyen.util.is_valid_hmac_notification` and `Adyen.util.is_valid_hmac` delete the entire "`additionalData`" key and dictionary from a notification, discarding any merchant provided `metadata` and other information in there.

Steps to reproduce:
1. Consume a webhook notification with HMAC
2. Run the item through above helper functions
3. See the "`additionalData`" is removed from the notification item, including all other data in there

Please see:
- https://github.com/Adyen/adyen-python-api-library/blob/a6f4bc670953d8d73d10c66830b294aff19ac420/Adyen/util.py#L43
- https://github.com/Adyen/adyen-python-api-library/blob/a6f4bc670953d8d73d10c66830b294aff19ac420/Adyen/util.py#L93

As a workaround, we have to deepcopy the entire notitication before validating it.

**Comment by AlexandrosMor** [comment]
Hello @dkms-its,

We are going to open an internal ticket for it and pick it up as soon as possible. In the mean time feel free to open a Pull Request and we are going to review it.

kind regards,
Alexandros
Adyen
