### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by icipiracy** [Adyen/adyen-python-api-library#16]
Current api version was only tested with Python 2.7, to cover more ground with developers and environments, Python 3 needs to be tested for as well.

Possibly the api does not many Python 2 specific features and so adaptation to Python 3 should not be complicated.

Some things unknown to me:
- Can there be 1 module that is both compatible with Python 2 and 3?
- If not, how can we easily 'convert' the current module to be Python 3 compatible?

**Comment by phobos1** [comment]
Please, put your tests and setup.py in repo, because without tests i can break something down with pull request.

**Comment by icipiracy** [comment]
We haven't started testing Python 3 yet. Test script still needs to be built in Python, currently we're testing on local server with client side scripts.

**Comment by icipiracy** [comment]
Added test scripts on todo list: #22

**Comment by icipiracy** [comment]
Found documentation and guides for making a library 'cross-compatible' with both Python 2 and 3:
- making Python lib compatible with both 2 and 3 may require importing ‘__future__’: https://stackoverflow.com/questions/7075082/what-is-future-in-python-used-for-and-how-when-to-use-it-and-how-it-works
- A guide from Python exists on how to make a library cross compatible: https://wiki.python.org/moin/PortingToPy3k/BilingualQuickRef
    - Because otherwise 2 codebases need to be maintained.
- Notes on Python 2 vs 3: https://wiki.python.org/moin/Python2orPython3

I have applied some of these steps already in commit: 39199415ea1697257f1b765d2345ccbcfc6462a6

Most print and except statements where already conforming with Python 3 syntax.

**Comment by Aleffio** [comment]
Latest release contains compatibility with Python3,

Regards,

Alessio
Adyen

**Comment by jaypeedevlin** [comment]
@Aleffio heads up, [these docs](http://adyen.github.io/adyen-python-api-library/index.html) still say 2.7 is required.  I would submit a PR to fix, but I don't think the repo backing the docs is public (or if it is, I can't find it).

**Comment by Aleffio** [comment]
Hi @jaypeedevlin ,

Thank you for reporting this!
I added 3.6 to the docs.

Regards,

Alessio
Adyen
