### ISSUE TITLE
Requesting release of latest develop branch to leverage refunds fix

### ISSUE THREAD

**Issue by cyancey** [Adyen/adyen-python-api-library#173]
**Is your feature request related to a problem? Please describe.**
I am currently working with the Adyen library to integrate various payments endpoints into a codebase and am hoping to use this library for refunds API calls. I noticed that on `develop`, there is a fix for a bug that prevents refund requests from working correctly but it has not yet been released.

Specifically, this is the commit I want released: https://github.com/Adyen/adyen-python-api-library/commit/7e50bc12f3974bcbba32fdd1e0b9b7a1f277aabd

**Describe the solution you'd like**
I would like the refund fix that was merged into `develop` to be incorporated into a release so I can pull the update via pip.

**Describe alternatives you've considered**
My alternatives are to stop my reliance on the published version of the package and either pull the develop branch into my codebase or roll my own refund request via another method.

**Comment by jillingk** [comment]
Hi @cyancey,

Massive apologies for the delayed respons, for some reason your issue flew a bit under the radar.

I have just created a new minor release and published it on PyPi, so you should be able to now use the refund request without any issues. Again apologies for the delay, let me know if you have any other issues/remarks regarding the library.

Best, Jilling
Adyen

**Comment by cyancey** [comment]
Thank you!
