### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by igorhoogerwoord** [Adyen/adyen-python-api-library#18]
All library features are tested, but a clean up/review is needed:
- make code more readable
- improve exception handling with more clear descriptions
- raise exceptions were possible instead of just returning false

PEP-8 style guide can provide a good guideline for code readability: https://www.python.org/dev/peps/pep-0008/

Hopefully someone can take a look and fix/provide feedback were needed.

**Comment by phobos1** [comment]
Good tool to make your code cleaner https://www.pylint.org/

**Comment by Aleffio** [comment]
The travis script now runs **_pycodestyle_** on the code in order to check for PEP-8 conventions.
It also runs **_pylint_** in the _**after_success**_ phase to have a more detailed code style analysis and score.

Thanks for the contributions.

Kind Regards,

Alessio
Adyen
