### ISSUE TITLE
User-Agent Header missing

### ISSUE THREAD

**Issue by icipiracy** [Adyen/adyen-python-api-library#20]
User-Agent header is created from the app name, library version and library type ( python ):
```python
self.user_agent = self.app_name + " " + self.USER_AGENT_SUFFIX + self.LIB_VERSION
```
However, when adding the 'User-Agent' header to a request it isn't sent ( or received ):
```
headers['User-Agent'] = self.user_agent
request = requests.post(url, auth=auth, data=data, json = json,headers=headers, timeout=timeout)
print request.headers # < 'User-Agent' header is not in here.
```
The User-Agent header defaults to "Apache-HttpClient\/4.4.1 (Java\/1.8.0_92)" on our servers. Thus it is either changed somewhere, set to default or it is not sent. The header not being sent should not result in it being "Apache-HttpClient\/4.4.1 (Java\/1.8.0_92)" so I think that can be ruled out as the issue.

**Comment by rikterbeek** [comment]
This is now implemented into the library.

Regards,
Rik
Adyen
