### ISSUE TITLE
Python Test Script

### ISSUE THREAD

**Issue by icipiracy** [Adyen/adyen-python-api-library#22]
Python test scripts for developers, should cover all library features.

Dev needs to enter test credentials locally, otherwise all tests fail with missing credentials and tests won't be of much use.

To avoid having credentials in source code, maybe it's useful to add function to load credentials from JSON file? This way a path can be given to credentials file which can easily be added to .gitignore.

**Comment by alexei** [comment]
FWIW Stripe reads the credentials from env vars with hard coded defaults; see https://github.com/stripe/stripe-python/blob/master/stripe/test/helper.py#L143

**Comment by rikterbeek** [comment]
@alexei,

Yes indeed we do not want to share any credentials so we used mockito for testing this is now added to the repository.

Regards,
Rik
Adyen
