### ISSUE TITLE
No build script in repo

### ISSUE THREAD

**Issue by nyuhuhuu** [Adyen/adyen-python-api-library#27]
Hi,

Is it intentional that the build script for this python package is maintained elsewhere? It would be great if it was part of the repository because then one could directly install Adyen from the git repo using pip. For this project [it was decided to remove it](https://github.com/Adyen/adyen-python-api-library/commit/1ae40046dd658ed801cb9467c746fdc384fd13b4) some time ago.

**Comment by rikterbeek** [comment]
Hi @nyuhuhuu,

Our package is op PIP. see https://pypi.python.org/pypi/Adyen/1.0.0
we will do a new release soon so we have a new package that support python 3.

Regards,
Rik
Adyen

**Comment by nyuhuhuu** [comment]
@rikterbeek Yes, I'm aware that it's up on PyPI. At the same time this only allows me to install the official releases. Meaning I cannot easily install the package straight from the develop branch here or even from my fork unless I provide a setup script. If you guys do not want to publish the setup script for some reason, it's fine for me, I just wanted to raise that this removes much flexibility and providing the setup script along with the repo is common practice among Python package maintainers.

**Comment by rikterbeek** [comment]
Hi @nyuhuhuu,

We added the scripts so we can automatically sync our github with our pypi package.

Regards,
Rik
Adyen

**Comment by nyuhuhuu** [comment]
@rikterbeek thank you! Works well!

**Comment by rikterbeek** [comment]
@nyuhuhuu,
Great! thank you for the value input really appreciate it.

Regards,
Rik
Adyen
