### ISSUE TITLE
Unhandled exceptions on json.loads give no clues on connection errors to Adyen

### ISSUE THREAD

**Issue by chronossc** [Adyen/adyen-python-api-library#43]
**Python version**: 2.7.12
**Library version**: 1.1.0, 1.2.0, development
**Description**

Sometimes we have big periods of time that we get following error from Adyen client:
```
ValueError('No JSON could be decoded')
``` 
To make the problem worse this exception tell us nothing about what we are sending and receiving to Adyen servers, and so we can't investigate the problem because we have no clues about it.

We need that devs handle the `json_lib.loads` call at https://github.com/Adyen/adyen-python-api-library/blob/1.1.0/Adyen/client.py#L413 and instead `ValueError` return an `AdyenInvalidRequestError` with request information so we can investigate the problem.

Cheers!

**Comment by Aleffio** [comment]
Hi @chronossc , 
on the development version we already have an if statement that checks if the raw_response exists: https://github.com/Adyen/adyen-python-api-library/blob/9f8b0ad29434cc43aaacf60cb1a309dd5668193b/Adyen/client.py#L429-L430
If the raw_response is empty, we still have the status code, which will make "self._handle_http_error" return the correct error message.

Kind Regards,

Alessio
Adyen

**Comment by chronossc** [comment]
That's awesome @Aleffio, maybe guys could backport that line to 1.1.1 and upload to pypi? 
I can't use development version in production and I can't upgrade to 1.2.x without take time to validate my entire system again.

**Comment by rikterbeek** [comment]
Hi @chronossc,

Best to just upgrade to latest version.
Adyen Python API Library 1.2.0
https://github.com/Adyen/adyen-python-api-library/releases/tag/1.2.0

Regards,
Rik
Adyen

**Comment by brianyan** [comment]
Hm, I'm also getting this error.

Python 2.7.11
Adyen Version 1.2.0

Stack trace listed below.
```
In [2]: AdyenWrapper.capture_charge('8815317748458061', 'USD', 1234)
peloton-api.ecomm.app.partners.adyen.client ERROR adyen_wrapper.capture_charge {"url":"http:\/\/127.0.0.1\/","psp_reference":"8815317748458061"}
Traceback (most recent call last):
  File "ecomm/app/partners/adyen/client.py", line 86, in capture_charge
    response = client.payment.capture(request=request)
  File "/Users/brian/Peloton/api/env/lib/python2.7/site-packages/Adyen/services.py", line 170, in capture
    response = self.client.call_api(request,self.service,action,**kwargs)
  File "/Users/brian/Peloton/api/env/lib/python2.7/site-packages/Adyen/client.py", line 285, in call_api
    status_code, headers, message)
  File "/Users/brian/Peloton/api/env/lib/python2.7/site-packages/Adyen/client.py", line 418, in _handle_response
    response = json_lib.loads(raw_response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
