### ISSUE TITLE
Keep a CHANGELOG

### ISSUE THREAD

**Issue by chronossc** [Adyen/adyen-python-api-library#44]
**Python version**: any
**Library version**: any
**Description**

Would be awesome to keep a CHANGELOG file with changes between releases so we don't need to compare tags with github (like in https://github.com/Adyen/adyen-python-api-library/compare/1.1.0...1.2.0)

**Comment by rikterbeek** [comment]
Hi @chronossc,

Changelog of the versions can be found in the releases. In this section we keep track of the bugs/features that are implemented. https://github.com/Adyen/adyen-python-api-library/releases

Regards,
Rik
Adyen
