### ISSUE TITLE
This line will never fire

### ISSUE THREAD

**Issue by artemijan** [Adyen/adyen-python-api-library#47]
This line will never fire
https://github.com/Adyen/adyen-python-api-library/blob/91b02d81f3a4f1d5a8a95427fcb15937bbc45530/Adyen/client.py#L531
because of there is line above
https://github.com/Adyen/adyen-python-api-library/blob/91b02d81f3a4f1d5a8a95427fcb15937bbc45530/Adyen/client.py#L493

**Comment by Aleffio** [comment]
Hi @artemijan ,
Thanks for the feedback, we will fix this line.

Regards,
Alessio
Adyen
