### ISSUE TITLE
Adyen v40

### ISSUE THREAD

**Issue by justinask7** [Adyen/adyen-python-api-library#54]
**Python version**: 3.6
**Library version**: 1.3.0
**Description**
Good day.
I see that this library is based on the Adyen v30, right?
Is there any chance that this library will be using v40 version of Adyen API soon? 
What are the main differences between v30 and v40? 

Cheers
Justinas

**Comment by Aleffio** [comment]
Hi @justinask7,
We are investigating the changes needed,
once done we will change the version to v40 and release a new version.

Regards,
Alessio
Adyen

**Comment by Aleffio** [comment]
Hi @justinask7,
In the v40 the main difference is that two new endpoints are supported: /authorise3ds2 and /retrieve3ds2Result, there are other tweaks, but they don't affect the library functionality.

Regards,
Alessio
Adyen
