### ISSUE TITLE
Changing the API endpoints

### ISSUE THREAD

**Issue by gitasf** [Adyen/adyen-python-api-library#55]
**Python version**: 2.7
**Library version**: x.y.z
**Description**
We are using the Adyen pyhton library to connect to Barclaycard smartpay. The library calls the Adyen test endpoints. Is there an option to change the endpoints being called by the python library as we need to call barclaycard smartpay endpoints

**Comment by AlexandrosMor** [comment]
Hello @gitasf,
This library is specific designed to be used only with Adyen endpoints. There is no option to adapt the library to other service.

Kind regards,
Alexandros Moraitis
Adyen
