### ISSUE TITLE
Unable to use API key for authentication

### ISSUE THREAD

**Issue by jarshwah** [Adyen/adyen-python-api-library#64]
**Python version**: 3.6
**Library version**: 2.0.0
**Description**

The `call_api` method does not correctly prioritise `xapikey` when it is passed through. The method asserts that both username and password have been set, so it's not possible to use the API key for regular api calls, like `/payment`.

See here:

https://github.com/Adyen/adyen-python-api-library/blob/928f6409ab6e2fac300b9fa29d89f3f508b23445/Adyen/client.py#L240
and 
https://github.com/Adyen/adyen-python-api-library/blob/928f6409ab6e2fac300b9fa29d89f3f508b23445/Adyen/client.py#L258

**Comment by Ishrock** [comment]
I have submitted a pull request that should resolve the issue: https://github.com/Adyen/adyen-python-api-library/pull/68
