### ISSUE TITLE
HTTPClient interface

### ISSUE THREAD

**Issue by Ishrock** [Adyen/adyen-python-api-library#65]
**Python version**: 3.7.2
**Library version**: 2.0.0

HTTPClient:
Interface between requests (line 140), pycurl (line 57), and urllib (line 196) should be the same.  'Requests' has xapikey as a parameter while pycurl, and urllib do not.

**Comment by AlexandrosMor** [comment]
Hello @Ishrock,

We are going to create an internal ticket for this issue and we will pick it up as soon as possible,

Kind regards,
Alexandros Moraitis
Adyen

**Comment by Ishrock** [comment]
Opened a pull request for the issue: https://github.com/Adyen/adyen-python-api-library/pull/68

**Comment by Ishrock** [comment]
closing, pr # 68 fixes issue
