### ISSUE TITLE
Is support for MarketPay planned?

### ISSUE THREAD

**Issue by tizz98** [Adyen/adyen-python-api-library#69]
Specifically these two services:

- https://cal-test.adyen.com/cal/services/Account // https://docs.adyen.com/api-explorer/#/Account/v5/overview
- https://cal-test.adyen.com/cal/services/Fund // https://docs.adyen.com/api-explorer/#/Fund/v3/overview

**Comment by AlexandrosMor** [comment]
Hello @tizz98,
It is not planned at the moment. If there is demand in the future from merchants we will include marketpay in python library.
kind regards,
Alexandros
