### ISSUE TITLE
Travis Build Failing on pycurl

### ISSUE THREAD

**Issue by Ishrock** [Adyen/adyen-python-api-library#82]
**Python version**: 2 and 3
**Library version**: 2.1.0
**Description**

Travis is failing to build pycurl from setup.py

  ----------------------------------------
  Failed building wheel for pycurl
  Running setup.py clean for pycurl
  Building wheel for docopt (setup.py) ... done
  Stored in directory: /home/travis/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
  Building wheel for wrapt (setup.py) ... done
  Stored in directory: /home/travis/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
Successfully built docopt wrapt
Failed to build pycurl
Installing collected packages: idna, urllib3, chardet, requests, pycurl, coverage, docopt, coveralls, isort, mccabe, lazy-object-proxy, wrapt, typed-ast, astroid, pylint, pycodestyle
  Running setup.py install for pycurl ... error
    Complete output from command /home/travis/virtualenv/python3.6.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-11_hg_43/pycurl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6v9198mt/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.6.7/include/site/python3.6/pycurl:
    Using curl-config (libcurl 7.47.0)
    Using SSL library: GnuTLS
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/curl
    copying python/curl/__init__.py -> build/lib.linux-x86_64-3.6/curl
    running build_ext
    building 'pycurl' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -DPYCURL_VERSION="7.43.0.3" -DHAVE_CURL_SSL=1 -DHAVE_CURL_GNUTLS=1 -DHAVE_CURL_SSL=1 -I/opt/python/3.6.7/include/python3.6m -c src/docstrings.c -o build/temp.linux-x86_64-3.6/src/docstrings.o
    In file included from src/docstrings.c:4:0:
    src/pycurl.h:168:30: fatal error: gnutls/gnutls.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/travis/virtualenv/python3.6.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-11_hg_43/pycurl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6v9198mt/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.6.7/include/site/python3.6/pycurl" failed with error code 1 in /tmp/pip-install-11_hg_43/pycurl/
The command "pip install requests pycurl mock coveralls pylint pycodestyle" failed and exited with 1 during .

**Comment by martinsrenato** [comment]
Hi @Ishrock,

Thanks for the input!
The test was failing because of a missing gnutls installation needed by pycurl.
We already fixed this issue on #84 and [the latest build is passing again](https://travis-ci.org/Adyen/adyen-python-api-library/builds/580609037).

Regards,
Renato
Adyen
