### ISSUE TITLE
Client Side Encryption (CSE)

### ISSUE THREAD

**Issue by mgurdal** [Adyen/adyen-python-api-library#83]
**Python version**: 3.7.4
**Library version**: 2.1.0
**Description**

Is there any way of encrypting card data similar to other SDK's CSE implementations?

**Comment by Ishrock** [comment]
I have had success using the Adyen SDK, Adyen Components, and the Adyen Secure Fields in the front-end to create tokens for card data.

https://docs.adyen.com/checkout/api-only

**Comment by AlexandrosMor** [comment]
Hello @mgurdal,

No the encryption is done by the CSE. You can check more in the documentation https://docs.adyen.com/checkout/api-only. I believe you already moved forward.

regards,
Alexandros

**Comment by mgurdal** [comment]
Thanks. I will check it.
