### ISSUE TITLE
Disabled X-API-KEY Authorization from `call_api`

### ISSUE THREAD

**Issue by samchristensen** [Adyen/adyen-python-api-library#86]
**Python version**: 2.7.16
**Library version**: 2.1.0
**Description**

When using the library to access functions on classes such as `adyen.recurring`, the underlying `call_api` function is used to actually make the api call. However, it doesn't allow for `X-API-KEY` as a valid authentication method as it `pops` it from the kwargs, and never passes it in as a potential named argument to the `self.http_client.request` call.

here is where it's popped

https://github.com/Adyen/adyen-python-api-library/blob/13e15445b34c8e5a4b5b727961009f865dccb47b/Adyen/client.py#L225

and then here is the call to request where it never gets passed back in

https://github.com/Adyen/adyen-python-api-library/blob/13e15445b34c8e5a4b5b727961009f865dccb47b/Adyen/client.py#L307

in contrast, here is the call to request from the different `call_checkout_api` function where `X-API-KEY` authentication does work

https://github.com/Adyen/adyen-python-api-library/blob/13e15445b34c8e5a4b5b727961009f865dccb47b/Adyen/client.py#L452

**Comment by Ishrock** [comment]
Pull request has been submitted for issue https://github.com/Adyen/adyen-python-api-library/pull/87

**Comment by AlexandrosMor** [comment]
Fixed #91
