### ISSUE TITLE
Ability to pin API versions

### ISSUE THREAD

**Issue by Ishrock** [Adyen/adyen-python-api-library#92]
**Python version**: all
**Library version**: 2.1.0
**Description**
It should be possible to ensure that the client is using the Adyen service version of the integration the user is using.  For example, currently the `settings.py` pins the Payment service version to `v49`, though the latest version is `v50`.  It is unclear when this client will bumped.  This could lead to unexpected behaviour, for example a new user writing their integration for v50 only to discover later on that the python client only targets v49.

My suggestion is to ensure the client is compatible with all versions, and allow the user to set what version they are targeting.  Update documentation explicitly stating the supported versions.

**Comment by jonaseriksson84** [comment]
Yup, as of now the latest API version is /v51/ but since the latest version of this python library only calls /v49/ the documentation may be incorrect. 

Especially since it is explicitly stated in the documentation that API version is bumped when incompatible changes happen.
