### ISSUE TITLE
Util generate_hpp_sig() value and hmac do not correspond

### ISSUE THREAD

**Issue by rousseldenis** [Adyen/adyen-python-api-library#96]
**Python version**: 2.7.16
**Library version**: 2.1.0 (and tested too with future 2.2.0)
**Description**
TEST ENVIRONMENT

Implemented webhook for Adyen notifications (https://docs.adyen.com/development-resources/notifications) and using Test Configuration form in Adyen backend.

Passed JSON received data from Adyen to generate_hpp_sig() function according to test here : https://github.com/Adyen/adyen-python-api-library/blob/develop/test/UtilTest.py#L13

The generated hmac does not correspond to the addtionnalData['hmacSignature'].

Even tested with future 2.2.0 function is_valid_hmac, returns False.

**Comment by rousseldenis** [comment]
@martinsrenato @rikterbeek @AlexandrosMor

**Comment by rikterbeek** [comment]
@rousseldenis,

Sorry for the late reply. We will investigate this and come back to you. 
Just to be sure you have enabled hmac calculation into the notification and get back the hmac singed data in additionalData ?

Regards,

**Comment by amuse-mkanerva** [comment]
Can confirm this is an issue on 2.2.0. See https://docs.adyen.com/development-resources/notifications/verify-hmac-signatures#example for sample payload that fails.
